<nav
  style:display="flex"
  style:justify-content="space-between"
  style:width="100%"
  style:padding="1rem"
  style:box-sizing="border-box"
>
  <div>
    FAR-NEAR
  </div>

  <ul
    style:list-style-type="none"
    style:display="flex"
    style:justify-content="space-between"
    style:gap="2rem"
    style:margin="0"
  >
    <li>
      About
    </li>
    <li>
      Newsletter
    </li>
    <li>
      Store
    </li>
    <li>
      Cart
    </li>
  </ul>
</nav>